### ISSUE TITLE
push() returns undefined if .catch() is used before .then()

### ISSUE THREAD

**Issue by Oltier** [sebasgarcep/firebase-admin-mock#10]
```javascript
static push(params) {
        const {path, child, data} = params;
        return admin.database().ref(path)
            .child(child)
            .push(data)
            .catch(function (err) {
                console.log(`Error pushing into ${path} due to ${err}`);
                return Promise.reject(`Error pushing into ${path} due to ${err}`);
            });
    }
```

On executing this code, Service.push({path, child, data}).then(...) return the following error:

> TypeError: Cannot read property 'then' of undefined

At the same time, the following set works properly:
```javascript
static set(params) {
        const {path, child, data} = params;
        return admin.database().ref(path)
            .child(child)
            .set(data)
            .catch(function (err) {
                console.log(`Error saving into ${path} due to ${err}`);
                return Promise.reject(`Error saving into ${path} due to ${err}`);
            });
    }
```

This probably, because .set returns a Promise, while .push returns a ThennableReference, which has a .catch property called `catch = () => {}` and obviously this one does not have a .then property.

The expected behavior would be that, if .push encounters an error, the function returns with a Promise.reject, so then chained functions can still execute properly.

**Comment by sebasgarcep** [comment]
@Oltier would you mind sending in a pull request?

**Comment by sebasgarcep** [comment]
`firebase-admin-mock` is being deprecated in favor of https://github.com/soumak77/firebase-mock.
