### ISSUE TITLE
update() doesn't work

### ISSUE THREAD

**Issue by esprehn** [sebasgarcep/firebase-admin-mock#11]
ex.

```
.update({
    'foo': 1,
    'bar': 2,
});
```

You end up with:

```
test: {
 bar: 2,
}
```

and the first write is lost.

The problem is in the loop inside .update() where it passes `data` repeatedly but should pass `acc`.

```
      const data = this._database._getData();
      const nextTree = updateKeys.reduce((acc, key) => {
        const location = [...this._pathArray, ...getPaths(key)];
        return setValue(data <--- THIS SHOULD BE acc , values[key], location);
      }, data);
```

**Comment by sebasgarcep** [comment]
Oh! You are correct, and thank you for pointing out where the mistake is. Would you mind submitting a pull request for this?

**Comment by sebasgarcep** [comment]
@esprehn I've already published a new version with your pull request. It must be `v0.0.9`. If something is wrong with the release don't hesitate to open a new issue.
