### ISSUE TITLE
val() does not respect query options

### ISSUE THREAD

**Issue by esprehn** [sebasgarcep/firebase-admin-mock#14]
```
ref.orderByChild('foo').startAt(1).endAt(2).once('value').then((snapshot) => snapshot.val());
```

It looks like the query options are being dynamically applied inside DataSnapshot but val() ignores them.

```
    this.val = () => {
      if (this._data === null || typeof this._data !== 'object') {
        return this._data;
      }
      return this._data.toJS();
    };
```

In general it looks like exportVal(), exists() and val() are all ignoring the options.

**Comment by sebasgarcep** [comment]
@esprehn Would you mind sending a pull request for this one?

**Comment by esprehn** [comment]
Sure thing, thanks for merging my last one so quickly!

**Comment by sebasgarcep** [comment]
`firebase-admin-mock` is being deprecated in favor of https://github.com/soumak77/firebase-mock.
