### ISSUE TITLE
createCustomToken in auth.js

### ISSUE THREAD

**Issue by ivanguimam** [sebasgarcep/firebase-admin-mock#15]
Why is the function ' createCustomToken ' in Auth commented?

**Comment by sebasgarcep** [comment]
@ivanguimam I've mostly only implemented the old firebase database. If you could provide a pull request for any of the missing features I would be happy to merge it. 😄

**Comment by sebasgarcep** [comment]
`firebase-admin-mock` is being deprecated in favor of https://github.com/soumak77/firebase-mock.
