### ISSUE TITLE
consider merging with firebase-mock

### ISSUE THREAD

**Issue by soumak77** [sebasgarcep/firebase-admin-mock#16]
I'm wondering if you would like to merge this library with [firebase-mock](https://soumak77.github.io/firebase-mock/).  I believe firebase-mock provides the same functionality as this library, however, if something is missing I am willing to help merge the missing functionality.

**Comment by sebasgarcep** [comment]
Hey @soumak77! I'm okay with deprecating this library if someone else can provide a more complete alternative. Is that what you mean by merging?

**Comment by soumak77** [comment]
@sebasgarcep yes.  I actively maintain the repo I listed above and I believe it has more a more complete mock of the `firebase-admin` SDK.

**Comment by sebasgarcep** [comment]
Then say no more! I'm deprecating this library in favor of yours.
